config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('ucsdparking.urls')),
]

ucsdparking/urls.py
from django.urls import path
from . import views

app_name = "ucsdparking"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('about', views.info_page_view, name='about'),
    path('usecases', views.usecases_page_view, name='usecases'),
    path('map', views.map_page_view, name='map'),
    path('dashboards', views.dashboard_page_view, name='dashboards'),
    path('dashboards2', views.dashboard2_page_view, name='dashboards2'),
    path('dashboards3', views.dashboard3_page_view, name='dashboards3'),
    path('dashboards4', views.dashboard4_page_view, name='dashboards4'),
    path('dashboards5', views.dashboard5_page_view, name='dashboards5'),
]

ucsdparking/models.py
from django.db import models

# Create your models here.

ucsdparking/views.py
from django.shortcuts import render

# Create your views here.

def home_page_view(request):
    return render(request, 'ucsdparking/home.html')

def info_page_view(request):
    return render(request, 'ucsdparking/info.html')

def usecases_page_view(request):
    return render(request, 'ucsdparking/useCases.html')

def map_page_view(request):
    return render(request, 'ucsdparking/map.html')

def dashboard_page_view(request):
    return render(request, 'ucsdparking/dashboard.html')

def dashboard2_page_view(request):
    return render(request, 'ucsdparking/dashboard2.html')

def dashboard3_page_view(request):
    return render(request, 'ucsdparking/dashboard4.html')

def dashboard4_page_view(request):
    return render(request, 'ucsdparking/dashboard5.html')

def dashboard5_page_view(request):
    return render(request, 'ucsdparking/dashboard3.html')

ucsdparking/templates/ucsdparking/dashboard.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-dashboard ">
    <h2 class="titlesPages">Compare Parking Lots</h2>
    <div class="tableau-dashboard-container">
        <script type='module' src='https://us-west-2b.online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js'></script>
        <tableau-viz id='tableau-viz' src='https://public.tableau.com/views/UCSDParking/Dashboard1?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link' width='800' height='640' hide-tabs toolbar='hidden' ></tableau-viz>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/dashboard2.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-dashboard">
    <h2 class="titlesPages">Compare Parking Spaces</h2>
    <div class="tableau-dashboard-container">
        <script type='module' src='https://us-west-2b.online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js'></script>
        <tableau-viz id='tableau-viz' src='https://public.tableau.com/views/UCSDParking/Dashboard2?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link' width='800' height='640' hide-tabs toolbar='hidden'></tableau-viz>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/dashboard3.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-dashboard">
    <h2 class="titlesPages">Covid Effect</h2>
    <div class="tableau-dashboard-container">
        <script type='module' src='https://us-west-2b.online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js'></script>
        <tableau-viz id='tableau-viz' src='https://public.tableau.com/views/UCSDParking/Dashboard3?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link' width='800' height='640' hide-tabs toolbar='hidden'></tableau-viz>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/dashboard4.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-dashboard">
    <h2 class="titlesPages">Rady Parking Lots</h2>
    <div class="tableau-dashboard-container">
        <script type='module' src='https://us-west-2b.online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js'></script>
        <tableau-viz id='tableau-viz' src='https://public.tableau.com/views/UCSDParking/Dashboard4?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link' width='800' height='640' hide-tabs toolbar='hidden'></tableau-viz>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/dashboard5.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-dashboard">
    <h2 class="titlesPages">Rady Time Parking</h2>
    <div class="tableau-dashboard-container">
        <script type='module' src='https://us-west-2b.online.tableau.com/javascripts/api/tableau.embedding.3.latest.min.js'></script>
        <tableau-viz id='tableau-viz' src='https://public.tableau.com/views/UCSDParking/Dashboard5?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link' width='800' height='640' hide-tabs toolbar='hidden'></tableau-viz>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/home.html
{% extends 'ucsdparking/layout.html' %} 
{% block main %} 
{% load static %}

<div class="hero-container">
    <div class="hero-image" id="heroImage">
        <img src="{% static 'ucsdparking/images/library.png' %}" alt="Image 1" class="slide">
        <img src="{% static 'ucsdparking/images/Rady.jpg' %}" alt="Image 2" class="slide">
        <img src="{% static 'ucsdparking/images/bear-1.jpeg' %}" alt="Image 3" class="slide">
        <img src="{% static 'ucsdparking/images/bridge.jpg' %}" alt="Image 4" class="slide">
    </div>

    <div class="hero-titles">
        <h2 class="centered-title">University of California - San Diego</h2>
        <h3 class="centered-subtitle">Parking Lots</h3>
    </div>

    <button id="prevBtn" class="nav-btn">❮</button>
    <button id="nextBtn" class="nav-btn">❯</button>
</div>

{% endblock %}

ucsdparking/templates/ucsdparking/info.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-about">
    <h2 class="titlesPages">About</h2>
    <div class="body-about">
        <p style="font-size: 20px; text-align: center;">Welcome to our comprehensive project, a pivotal component of 
            the Collecting and Analyze Large Data course at the University of California - San Diego, Rady School of Management. 
            This initiative is not just an academic exercise; it's a practical solution tailored to 
            enhance the daily experiences of our university community. By meticulously gathering and 
            examining extensive parking lot inventory data, we aim to shed light on the fluctuating 
            demands of park usage throughout the year. Our objective is to provide actionable insights 
            that facilitate better planning and resource allocation for students and staff alike. 
            Delve into our detailed analysis and discover how we're harnessing the power of big data 
            to foster a more efficient and accommodating campus environment.
            <h1 class="titlesPagesAbouth2">Data</h1>
            <p style="font-size: 20px; text-align: center;">After comprehensive research, our team has procured an extensive dataset detailing parking lot occupancy across 
                the UCSD campuses in La Jolla and Hillcrest. This rich dataset encompasses a decade-long survey of parking spaces, 
                capturing hourly occupancy details from 8 a.m. to 5 p.m., Monday through Thursday. Spanning from 2000 to the present, 
                it offers an in-depth view of parking dynamics over the years.</p>
            <p style="font-size: 20px; text-align: center;">
                For our analysis, we focused on data post-2018, providing us with a unique opportunity to examine the impact of the COVID-19 pandemic on campus parking trends.
                 Our approach involved dissecting the data by various categories including individual lots, structures, neighborhoods, areas, and specific locations. 
                 This granular analysis allows for a nuanced understanding of parking occupancy patterns during this unprecedented period. Importantly, the data we analyzed 
                 is based on one day of observation per parking lot per quarter, with observations taken every hour of that day. This approach ensures a comprehensive view of 
                 parking dynamics over different times and seasons.</p>
            <p style="font-size: 20px; text-align: center;">You can access and explore the dataset used for this project <a href="https://rmp-wapps.ucsd.edu/TS/Survey/Parking%20Space%20Inventory/Quarterly%20Tables/Contents.html" target="_blank" style="color: white;">here</a>.</p>
            <h1 class="titlesPagesAbouth2">Methodology</h1>
            <div style="text-align: center;">
                <img style="width: 65%;" src="{% static 'ucsdparking/images/Flow.png' %}" alt="Flow">
            </div>
        </p>
        <div style="padding: 15px;"></div>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/layout.html
<!DOCTYPE html>
{% load static %} {% with url_name=request.resolver_match.url_name %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <link
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap"
            rel="stylesheet">
        
        <!-- Favicon link -->
        <link rel="icon" href="{% static 'ucsdparking/images/icon.png' %}" type="image/png">
    
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Racing+Sans+One&family=Roboto:wght@300&display=swap"
            rel="stylesheet">
        <title>UCSD Parking</title>
        <link rel="stylesheet" type="text/css"
            href="{% static 'ucsdparking/css/styles.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{% static 'ucsdparking/javascript/javascript.js' %}"></script>
        <meta name="description" content="Description of your page">
        <meta name="author" content="Martim Teixeira">
    </head>
    
    <body>
        <header class="topbar">
            <div class="logo">
                <a href="{% url 'ucsdparking:home' %}">
                    <img
                        src="{% static 'ucsdparking/images/ucsd-logo.png' %}"
                        alt="Logo">
                </a>
            </div>
            <nav class="navbar">
                <a href="{% url 'ucsdparking:home' %}" class="{% if url_name == 'home' %}active{% endif %}">Home</a>
                <a href="{% url 'ucsdparking:about' %}" class="{% if url_name == 'about' %}active{% endif %}">About</a>
                <a href="{% url 'ucsdparking:usecases' %}" class="{% if url_name == 'usecases' %}active{% endif %}">Use Cases</a>
                <a href="{% url 'ucsdparking:map' %}" class="{% if url_name == 'map' %}active{% endif %}">Map UCSD</a>
                <div class="dropdown">
                    <a href="" class="{% if url_name == 'dashboards' or url_name == 'dashboards2' or url_name == 'dashboards3' or url_name == 'dashboards4' or url_name == 'dashboards5' %}active{% endif %}">Dashboards <span class="dropdown-arrow">&#9662;</span></a>
                        <div class="dropdown-content">
                        <a href="{% url 'ucsdparking:dashboards' %}" class="{% if url_name == 'dashboards' %}active{% endif %}">Compare Parking Lots</a>
                        <a href="{% url 'ucsdparking:dashboards2' %}" class="{% if url_name == 'dashboards2' %}active{% endif %}">Compare Parking Spaces</a>
                        <a href="{% url 'ucsdparking:dashboards3' %}" class="{% if url_name == 'dashboards3' %}active{% endif %}">Rady Parking Lots</a>
                        <a href="{% url 'ucsdparking:dashboards4' %}" class="{% if url_name == 'dashboards4' %}active{% endif %}">Rady Time Parking</a>
                        <a href="{% url 'ucsdparking:dashboards5' %}" class="{% if url_name == 'dashboards5' %}active{% endif %}">Covid Effect</a>
                    </div>
                </div>
            </nav>
        </header>
        <main>{% block main %} {% endblock main %}</main>
    </body>
    <footer>
        <div class="footer-content">
            <p>Collecting and Analyze Large Data</p>
            <p>Presented by Grace Kim, Jeremy Edwards, Martim Teixeira, Shridhar Rawat</p>
            <p>&copy; 2023 Martim Teixeira</p>
        </div>
    </footer>
</html>
{% endwith %}

ucsdparking/templates/ucsdparking/map.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-map">
    <h2 class="titlesPages">Map UCSD</h2>
    <div class="map-container">
        <iframe src="https://map.concept3d.com/?id=1005#!ce/17201?ct/25239,29254,29255,29256,29257,29258,29263,29264,29265,29266,58265,61945,61946,61947,61948,61965?s/?mc/32.88081304251091,-117.2313149235207?z/14.7040482541956?lvl/0" width="100%" height="100%" title="University of California San Diego" frameBorder="0" scrolling="no" style="border:0px solid #fff; margin:0; padding:0;"></iframe>
    </div>
</div>
{% endblock %}

ucsdparking/templates/ucsdparking/useCases.html
{% extends 'ucsdparking/layout.html' %} {% block main %} {% load static %}
<div class="hero-container-about">
    <div class="body-about">
        <p style="font-size: 20px; text-align: center;">
            <h1 class="titlesPagesAbouth2" style="font-size: 50px; color: white;">Use Case UCSD</h1>
            <p style="font-size: 20px; text-align: center;">A faculty member at UCSD plans to schedule a meeting with students and other staff members at the Geisel Library.
                They use the website to check the availability of parking spaces in lots close to the Rady School of Management. 
                By viewing the dashboard, they can determine the best time to schedule the meeting, ensuring that all attendees will find parking conveniently. 
                This tool also allows students and staff to plan their campus visits efficiently, selecting times when parking spaces are more readily available.</p>
            <h1 class="titlesPagesAbouth2" style="font-size: 50px; color: white;">Use Case Rady School of Management</h1>
            <p style="font-size: 20px; text-align: center;">Parents visiting their child at UCSD for a special event at the Rady School of Management utilize the 
                website to check parking lot availability. They choose the years and quarters from the options in the list, related to the date of their visit to 
                view the average availability of the parking lots, parking spaces and at the hours of the day selected. This information helps them to plan their 
                visit better, ensuring they arrive on time for the event. They got a permit of visitor from the permits website, so it's important to check the 
                availability of this parking spaces.
            </p>
            <h1 class="titlesPagesAbouth2" style="font-size: 50px; color: white;">Large Scale Use Cases</h1>
            <p style="font-size: 20px; text-align: center;">This tool would be well suited for integration with the UCSD parking services website, as it utilizes their 
                interactive map to find specific parking lots available to students as well as information regarding their permit types. If UCSD Parking decided to 
                integrate this tool, they could directly filter by permit type based on availability to search for lots with more than X% of spots expected to be 
                available at a given time to help individuals decide whether or not to purchase a parking pass for use at that time, or whether they would be better 
                off finding other options for transportation.
            </p>
            <p style="font-size: 20px; text-align: center;">For UCSD Campus planning, this tool's integration could serve as a valuable asset in the future development 
                of parking. With UCSD's ongoing expansion and the increase in student and faculty numbers, more parking will inevitably be needed. Utilizing data from 
                this tool, the school can identify which parking lots are facing challenges in providing adequate parking and which are underutilized. This information 
                would enable proactive steps to increase parking in areas with high demand and potentially repurpose areas around underutilized lots for new buildings, 
                dorms, or other campus needs.</p>
        </p>
        <div style="padding: 15px;"></div>
    </div>
</div>
{% endblock %}